/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import backend.GestorArchivos;
import backend.Operador;
import conexion.Connect;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import jxl.write.WriteException;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Sebastian
 */
public class Menu extends javax.swing.JFrame {
    
    private Connect c = new Connect();
    private Operador operador;
    private GestorArchivos GA=new GestorArchivos();

    /**
     * Creates new form Menu
     *
     * @param operador
     */
    public Menu(Operador operador) {
        this.operador = operador;
        initComponents();
        userView.setText(operador.getNombre() + " " + operador.getApellidos());
        this.menuNormal.setVisible(true);
        this.usuariosPane.setVisible(false);
        this.SectoresPage.setVisible(false);
        this.institucionesPage.setVisible(false);
        this.delincuentesPage.setVisible(false);
        this.delitosPage.setVisible(false);
        this.reportesPage.setVisible(false);
        this.comunaPage.setVisible(false);
        permisos();
    }
    
    private void permisos() {
        String rango = operador.getRango();
        if (rango.equals("AdministradorGeneral")) {
            this.homeButton.setVisible(true);
            this.usuariosButton.setVisible(true);
            this.sectoresButton.setVisible(true);
            this.institucionesButton.setVisible(true);
            this.delincuentesButton.setVisible(true);
            this.delitosButton.setVisible(true);
            this.reportesButton.setVisible(true);
            this.comunaButton.setEnabled(true);
        } else if (rango.equals("JefeDeZona")) {
            this.homeButton.setVisible(true);
            this.usuariosButton.setVisible(true);
            this.sectoresButton.setVisible(true);
            this.institucionesButton.setVisible(true);
            this.delincuentesButton.setVisible(true);
            this.delitosButton.setVisible(true);
            this.reportesButton.setVisible(true);
            this.comunaButton.setEnabled(true);
        } else {
            this.homeButton.setEnabled(false);
            this.usuariosButton.setEnabled(false);
            this.sectoresButton.setEnabled(false);
            this.institucionesButton.setEnabled(false);
            this.delincuentesButton.setEnabled(true);
            this.delitosButton.setEnabled(true);
            this.reportesButton.setEnabled(true);
            this.comunaButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paginas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menuNormal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usuariosPane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        UsuarioRut = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UsuarioNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        UsuarioApellido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        UsuarioInstitucionBoxUsuarios = new javax.swing.JComboBox<>();
        RadioAdministradorGeneral = new javax.swing.JRadioButton();
        RadioJefeDeZona = new javax.swing.JRadioButton();
        RadioOperador = new javax.swing.JRadioButton();
        UsuarioCrearUsuario = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        UsuarioComprobar = new javax.swing.JButton();
        UsuarioEditarUsuario = new javax.swing.JButton();
        UsuarioEliminarUsuario = new javax.swing.JButton();
        UsuarioContrasena = new javax.swing.JPasswordField();
        institucionesPage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        InstitucionesCrear = new javax.swing.JButton();
        InstitucionesEditar = new javax.swing.JButton();
        InstitucionesEliminar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        InstitucionesCodigo = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        InstitucionesNombre = new javax.swing.JTextField();
        reportesPage = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        delitosPage = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        delincuentesPage = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        SectoresPage = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        SectoresCodigo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        SectoresNombre = new javax.swing.JTextField();
        SectoresDescripcion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        SectoresInstitucion = new javax.swing.JComboBox<>();
        SectoresEditar = new javax.swing.JButton();
        SectoresCrear = new javax.swing.JButton();
        SectoresEliminar = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        comunaPage = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        botonera = new javax.swing.JPanel();
        userView = new javax.swing.JLabel();
        reportesButton = new javax.swing.JButton();
        institucionesButton = new javax.swing.JButton();
        delincuentesButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        usuariosButton = new javax.swing.JButton();
        delitosButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        sectoresButton = new javax.swing.JButton();
        comunaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paginas.setBackground(new java.awt.Color(206, 51, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PREVCRIM.png"))); // NOI18N

        menuNormal.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenidos a este Sistema Integrado de Registro para la Prevención");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistema creado por : Sebastian Vargas y Gaston Velasquez");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuNormalLayout = new javax.swing.GroupLayout(menuNormal);
        menuNormal.setLayout(menuNormalLayout);
        menuNormalLayout.setHorizontalGroup(
            menuNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        menuNormalLayout.setVerticalGroup(
            menuNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuNormalLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 541, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        usuariosPane.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Usuarios");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Rut: ");

        UsuarioRut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Contraseña:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Nombre:");

        UsuarioNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Apellido:");

        UsuarioApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Institucion:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Rango:");

        UsuarioInstitucionBoxUsuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UsuarioInstitucionBoxUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        RadioAdministradorGeneral.setText("Administrador General");

        RadioJefeDeZona.setText("Jefe de Zona");

        RadioOperador.setText("Operador");

        UsuarioCrearUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsuarioCrearUsuario.setText("Crear usuario");
        UsuarioCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioCrearUsuarioActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setText("Ver usuarios");

        UsuarioComprobar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsuarioComprobar.setText("Comprobar");
        UsuarioComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioComprobarActionPerformed(evt);
            }
        });

        UsuarioEditarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsuarioEditarUsuario.setText("Editar usuario");
        UsuarioEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioEditarUsuarioActionPerformed(evt);
            }
        });

        UsuarioEliminarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UsuarioEliminarUsuario.setText("Eliminar");
        UsuarioEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioEliminarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usuariosPaneLayout = new javax.swing.GroupLayout(usuariosPane);
        usuariosPane.setLayout(usuariosPaneLayout);
        usuariosPaneLayout.setHorizontalGroup(
            usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(usuariosPaneLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosPaneLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RadioAdministradorGeneral, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, usuariosPaneLayout.createSequentialGroup()
                                .addComponent(RadioOperador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RadioJefeDeZona)))
                        .addContainerGap())
                    .addGroup(usuariosPaneLayout.createSequentialGroup()
                        .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(usuariosPaneLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, usuariosPaneLayout.createSequentialGroup()
                                .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UsuarioRut, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(UsuarioContrasena)))
                            .addGroup(usuariosPaneLayout.createSequentialGroup()
                                .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UsuarioInstitucionBoxUsuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UsuarioApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                        .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(usuariosPaneLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(UsuarioComprobar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosPaneLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))))
            .addGroup(usuariosPaneLayout.createSequentialGroup()
                .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosPaneLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(UsuarioCrearUsuario)
                        .addGap(30, 30, 30)
                        .addComponent(UsuarioEditarUsuario))
                    .addGroup(usuariosPaneLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(UsuarioEliminarUsuario)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        usuariosPaneLayout.setVerticalGroup(
            usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosPaneLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(88, 88, 88)
                .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(UsuarioComprobar))
                .addGap(30, 30, 30)
                .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(UsuarioContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(UsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(UsuarioApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(usuariosPaneLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(UsuarioInstitucionBoxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(RadioOperador)
                    .addComponent(RadioJefeDeZona))
                .addGap(18, 18, 18)
                .addComponent(RadioAdministradorGeneral)
                .addGap(18, 18, 18)
                .addGroup(usuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsuarioCrearUsuario)
                    .addComponent(UsuarioEditarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsuarioEliminarUsuario)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        institucionesPage.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Instituciones");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Ver instituciones");

        InstitucionesCrear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        InstitucionesCrear.setText("Crear");
        InstitucionesCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstitucionesCrearActionPerformed(evt);
            }
        });

        InstitucionesEditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        InstitucionesEditar.setText("Editar");
        InstitucionesEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstitucionesEditarActionPerformed(evt);
            }
        });

        InstitucionesEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        InstitucionesEliminar.setText("Eliminar");
        InstitucionesEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstitucionesEliminarActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Codigo :");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Comprobar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Nombre :");

        javax.swing.GroupLayout institucionesPageLayout = new javax.swing.GroupLayout(institucionesPage);
        institucionesPage.setLayout(institucionesPageLayout);
        institucionesPageLayout.setHorizontalGroup(
            institucionesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(institucionesPageLayout.createSequentialGroup()
                .addGroup(institucionesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(institucionesPageLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel5))
                    .addGroup(institucionesPageLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(institucionesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(institucionesPageLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(InstitucionesEditar))
                            .addGroup(institucionesPageLayout.createSequentialGroup()
                                .addComponent(InstitucionesCrear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InstitucionesEliminar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(institucionesPageLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(institucionesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(institucionesPageLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InstitucionesCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(institucionesPageLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InstitucionesNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(93, 93, 93))
        );
        institucionesPageLayout.setVerticalGroup(
            institucionesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(institucionesPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(institucionesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(institucionesPageLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(institucionesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InstitucionesCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jButton6))
                        .addGap(28, 28, 28)
                        .addGroup(institucionesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(InstitucionesNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(institucionesPageLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButton1)))
                .addGap(26, 26, 26)
                .addGroup(institucionesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InstitucionesCrear)
                    .addComponent(InstitucionesEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InstitucionesEditar)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        reportesPage.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("reportes");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Mostrar delincuentes por comuna de residencia");

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton13.setText("Mostrar delincuentes Ordenados alfabeticamente");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton14.setText("Mostrar delincuentes por parentesco entre ellos");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton15.setText("Listado de delincuentes agrupados por delito cometido");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton16.setText("Mostrar rankin comunas con mayor cantidad de delitos dentro de un rango de fechas");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton18.setText("Listado histórico de delitos ocurridos por sectores");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton24.setText("Mostrar delincuentes por ultimo lugar visto");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton25.setText("Listado de delitos ocurridos por comuna o sector, en fechas específicas");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportesPageLayout = new javax.swing.GroupLayout(reportesPage);
        reportesPage.setLayout(reportesPageLayout);
        reportesPageLayout.setHorizontalGroup(
            reportesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(reportesPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(reportesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reportesPageLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        reportesPageLayout.setVerticalGroup(
            reportesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportesPageLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(96, 96, 96)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(reportesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(reportesPageLayout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(472, Short.MAX_VALUE)))
        );

        delitosPage.setBackground(new java.awt.Color(204, 204, 204));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("delitos");

        javax.swing.GroupLayout delitosPageLayout = new javax.swing.GroupLayout(delitosPage);
        delitosPage.setLayout(delitosPageLayout);
        delitosPageLayout.setHorizontalGroup(
            delitosPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        delitosPageLayout.setVerticalGroup(
            delitosPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delitosPageLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addContainerGap(564, Short.MAX_VALUE))
        );

        delincuentesPage.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Delincuentes");

        javax.swing.GroupLayout delincuentesPageLayout = new javax.swing.GroupLayout(delincuentesPage);
        delincuentesPage.setLayout(delincuentesPageLayout);
        delincuentesPageLayout.setHorizontalGroup(
            delincuentesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        delincuentesPageLayout.setVerticalGroup(
            delincuentesPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delincuentesPageLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addContainerGap(561, Short.MAX_VALUE))
        );

        SectoresPage.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Sectores");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Codigo :");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Comprobar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Nombre: ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Descripcion :");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Institucion :");

        SectoresInstitucion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SectoresInstitucion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        SectoresEditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SectoresEditar.setText("Editar");

        SectoresCrear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SectoresCrear.setText("Crear");

        SectoresEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SectoresEliminar.setText("Eliminar");

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setText("Ver Instituciones");

        javax.swing.GroupLayout SectoresPageLayout = new javax.swing.GroupLayout(SectoresPage);
        SectoresPage.setLayout(SectoresPageLayout);
        SectoresPageLayout.setHorizontalGroup(
            SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(SectoresPageLayout.createSequentialGroup()
                .addGroup(SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SectoresPageLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SectoresPageLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SectoresCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7))
                            .addGroup(SectoresPageLayout.createSequentialGroup()
                                .addGroup(SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SectoresInstitucion, 0, 342, Short.MAX_VALUE)
                                    .addComponent(SectoresNombre)
                                    .addComponent(SectoresDescripcion)))))
                    .addGroup(SectoresPageLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SectoresPageLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(SectoresEditar))
                            .addGroup(SectoresPageLayout.createSequentialGroup()
                                .addComponent(SectoresCrear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SectoresEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton12)))))
                .addGap(20, 20, 20))
        );
        SectoresPageLayout.setVerticalGroup(
            SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SectoresPageLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(137, 137, 137)
                .addGroup(SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SectoresCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SectoresNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(SectoresDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(SectoresInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SectoresPageLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(SectoresPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SectoresCrear)
                            .addComponent(SectoresEliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SectoresPageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12)
                        .addGap(19, 19, 19)))
                .addComponent(SectoresEditar)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        comunaPage.setBackground(new java.awt.Color(204, 204, 204));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Comuna");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Codigo :");

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton19.setText("Comprobar");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Nombre:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Sector :");

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton20.setText("Crear");

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton21.setText("Eliminar");

        jButton22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton22.setText("Editar");

        jButton23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton23.setText("Ver Instituciones");

        javax.swing.GroupLayout comunaPageLayout = new javax.swing.GroupLayout(comunaPage);
        comunaPage.setLayout(comunaPageLayout);
        comunaPageLayout.setHorizontalGroup(
            comunaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comunaPageLayout.createSequentialGroup()
                .addGroup(comunaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comunaPageLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(comunaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(comunaPageLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(comunaPageLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton19))
                    .addGroup(comunaPageLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(comunaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton21)
                            .addGroup(comunaPageLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(330, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comunaPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comunaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comunaPageLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comunaPageLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jButton20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton23)
                        .addGap(48, 48, 48))))
            .addGroup(comunaPageLayout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jButton22)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        comunaPageLayout.setVerticalGroup(
            comunaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comunaPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(105, 105, 105)
                .addGroup(comunaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comunaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(comunaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(46, 46, 46)
                .addGroup(comunaPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton23)
                    .addComponent(jButton20)
                    .addComponent(jButton21))
                .addGap(18, 18, 18)
                .addComponent(jButton22)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paginasLayout = new javax.swing.GroupLayout(paginas);
        paginas.setLayout(paginasLayout);
        paginasLayout.setHorizontalGroup(
            paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginasLayout.createSequentialGroup()
                .addContainerGap(712, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addComponent(usuariosPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(institucionesPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(menuNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SectoresPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(delincuentesPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(delitosPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(reportesPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(comunaPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paginasLayout.setVerticalGroup(
            paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuariosPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paginasLayout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(institucionesPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paginasLayout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(menuNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paginasLayout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(SectoresPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paginasLayout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(delincuentesPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paginasLayout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(delitosPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paginasLayout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(reportesPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
            .addGroup(paginasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paginasLayout.createSequentialGroup()
                    .addContainerGap(81, Short.MAX_VALUE)
                    .addComponent(comunaPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(4, 4, 4)))
        );

        getContentPane().add(paginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 900, 650));

        botonera.setBackground(new java.awt.Color(255, 255, 255));

        userView.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userView.setText("Sebastian Vargas");

        reportesButton.setBackground(new java.awt.Color(255, 255, 255));
        reportesButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reportesButton.setForeground(new java.awt.Color(206, 51, 0));
        reportesButton.setText("Reportes");
        reportesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesButtonActionPerformed(evt);
            }
        });

        institucionesButton.setBackground(new java.awt.Color(255, 255, 255));
        institucionesButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        institucionesButton.setForeground(new java.awt.Color(206, 51, 0));
        institucionesButton.setText("Instituciones");
        institucionesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                institucionesButtonActionPerformed(evt);
            }
        });

        delincuentesButton.setBackground(new java.awt.Color(255, 255, 255));
        delincuentesButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delincuentesButton.setForeground(new java.awt.Color(206, 51, 0));
        delincuentesButton.setText("Delincuentes");
        delincuentesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delincuentesButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenido");

        usuariosButton.setBackground(new java.awt.Color(255, 255, 255));
        usuariosButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usuariosButton.setForeground(new java.awt.Color(206, 51, 0));
        usuariosButton.setText("Usuarios");
        usuariosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosButtonActionPerformed(evt);
            }
        });

        delitosButton.setBackground(new java.awt.Color(255, 255, 255));
        delitosButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delitosButton.setForeground(new java.awt.Color(206, 51, 0));
        delitosButton.setText("Delitos");
        delitosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delitosButtonActionPerformed(evt);
            }
        });

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        homeButton.setForeground(new java.awt.Color(206, 51, 0));
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        sectoresButton.setBackground(new java.awt.Color(255, 255, 255));
        sectoresButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        sectoresButton.setForeground(new java.awt.Color(206, 51, 0));
        sectoresButton.setText("Sectores");
        sectoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectoresButtonActionPerformed(evt);
            }
        });

        comunaButton.setBackground(new java.awt.Color(255, 255, 255));
        comunaButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        comunaButton.setForeground(new java.awt.Color(206, 51, 0));
        comunaButton.setText("Comunas");
        comunaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comunaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoneraLayout = new javax.swing.GroupLayout(botonera);
        botonera.setLayout(botoneraLayout);
        botoneraLayout.setHorizontalGroup(
            botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reportesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addComponent(userView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(institucionesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(delincuentesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usuariosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(delitosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sectoresButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(comunaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botoneraLayout.setVerticalGroup(
            botoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoneraLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userView)
                .addGap(37, 37, 37)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuariosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(institucionesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sectoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(comunaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delincuentesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delitosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        getContentPane().add(botonera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 648));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuariosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosButtonActionPerformed
        // TODO add your handling code here:
        this.menuNormal.setVisible(false);
        this.usuariosPane.setVisible(true);
        this.SectoresPage.setVisible(false);
        this.institucionesPage.setVisible(false);
        this.delincuentesPage.setVisible(false);
        this.delitosPage.setVisible(false);
        this.reportesPage.setVisible(false);
        this.comunaPage.setVisible(false);
        if (operador.getRango().equals("AdministradorGeneral")) {
            c.loadInstituciones2(this.UsuarioInstitucionBoxUsuarios);
        } else {
            c.loadInstituciones1(this.UsuarioInstitucionBoxUsuarios, operador);
            
        }
        ButtonGroup rb = new ButtonGroup();
        rb.add(this.RadioAdministradorGeneral);
        rb.add(this.RadioJefeDeZona);
        rb.add(this.RadioOperador);
        this.UsuarioApellido.setEditable(false);
        this.UsuarioInstitucionBoxUsuarios.setEnabled(false);
        this.UsuarioEliminarUsuario.setEnabled(false);
        this.UsuarioCrearUsuario.setEnabled(false);
        this.UsuarioEditarUsuario.setEnabled(false);
        this.UsuarioContrasena.setEditable(false);
        this.RadioAdministradorGeneral.setEnabled(false);
        this.RadioOperador.setEnabled(false);
        this.RadioJefeDeZona.setEnabled(false);
        this.UsuarioNombre.setEditable(false);
        this.UsuarioRut.setEditable(true);
        
        this.UsuarioApellido.setText("");
        this.UsuarioContrasena.setText("");
        this.UsuarioNombre.setText("");
        this.UsuarioRut.setText("");
    }//GEN-LAST:event_usuariosButtonActionPerformed
    

    private void institucionesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_institucionesButtonActionPerformed
        // TODO add your handling code here:
        this.menuNormal.setVisible(false);
        this.usuariosPane.setVisible(false);
        this.SectoresPage.setVisible(false);
        this.institucionesPage.setVisible(true);
        this.delincuentesPage.setVisible(false);
        this.delitosPage.setVisible(false);
        this.reportesPage.setVisible(false);
        institucionesDefault();
    }//GEN-LAST:event_institucionesButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.menuNormal.setVisible(true);
        this.usuariosPane.setVisible(false);
        this.SectoresPage.setVisible(false);
        this.institucionesPage.setVisible(false);
        this.delincuentesPage.setVisible(false);
        this.delitosPage.setVisible(false);
        this.reportesPage.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Desktop enlace = Desktop.getDesktop();
        try {
            enlace.browse(new URI("https://github.com/hacefrio/tesis"));
        } catch (IOException | URISyntaxException e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabel6MouseExited

    private void sectoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectoresButtonActionPerformed
        // TODO add your handling code here:
        this.menuNormal.setVisible(false);
        this.usuariosPane.setVisible(false);
        this.SectoresPage.setVisible(true);
        this.institucionesPage.setVisible(false);
        this.delincuentesPage.setVisible(false);
        this.delitosPage.setVisible(false);
        this.reportesPage.setVisible(false);
        this.comunaPage.setVisible(false);
        sectoresDefault();
    }//GEN-LAST:event_sectoresButtonActionPerformed

    private void delincuentesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delincuentesButtonActionPerformed
        // TODO add your handling code here:
        this.menuNormal.setVisible(false);
        this.usuariosPane.setVisible(false);
        this.SectoresPage.setVisible(false);
        this.institucionesPage.setVisible(false);
        this.delincuentesPage.setVisible(true);
        this.delitosPage.setVisible(false);
        this.reportesPage.setVisible(false);
    }//GEN-LAST:event_delincuentesButtonActionPerformed

    private void delitosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delitosButtonActionPerformed
        // TODO add your handling code here:
        this.menuNormal.setVisible(false);
        this.usuariosPane.setVisible(false);
        this.SectoresPage.setVisible(false);
        this.institucionesPage.setVisible(false);
        this.delincuentesPage.setVisible(false);
        this.delitosPage.setVisible(true);
        this.reportesPage.setVisible(false);
        this.comunaPage.setVisible(false);
    }//GEN-LAST:event_delitosButtonActionPerformed

    private void reportesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesButtonActionPerformed
        // TODO add your handling code here:
        this.menuNormal.setVisible(false);
        this.usuariosPane.setVisible(false);
        this.SectoresPage.setVisible(false);
        this.institucionesPage.setVisible(false);
        this.delincuentesPage.setVisible(false);
        this.delitosPage.setVisible(false);
        this.reportesPage.setVisible(true);
        this.comunaPage.setVisible(false);
    }//GEN-LAST:event_reportesButtonActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void UsuarioComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioComprobarActionPerformed
        // TODO add your handling code here:
        String consulta = c.comprobarUsuariosRutPermisos(this.UsuarioRut.getText(), operador);
        this.UsuarioInstitucionBoxUsuarios.removeAllItems();
        if (operador.getRango().equals("AdministradorGeneral")) {
            c.loadInstituciones2(this.UsuarioInstitucionBoxUsuarios);
        } else {
            c.loadInstituciones1(this.UsuarioInstitucionBoxUsuarios, operador);
            
        }
        if (consulta.equals("si")) {
            this.UsuarioRut.setEditable(false);
            JOptionPane.showMessageDialog(null, "El usuario ya existe");
            this.UsuarioApellido.setEditable(true);
            this.UsuarioInstitucionBoxUsuarios.setEnabled(true);
            this.UsuarioApellido.setEditable(true);
            this.UsuarioContrasena.setEditable(true);
            this.RadioAdministradorGeneral.setEnabled(true);
            this.RadioOperador.setEnabled(true);
            this.RadioJefeDeZona.setEnabled(true);
            this.UsuarioNombre.setEditable(true);
            this.UsuarioEliminarUsuario.setEnabled(true);
            this.UsuarioCrearUsuario.setEnabled(false);
            this.UsuarioEditarUsuario.setEnabled(true);
            Operador usuario = new Operador();
            c.setOperador2(this.UsuarioRut.getText(), usuario);
            this.UsuarioApellido.setText(usuario.getApellidos());
            this.UsuarioNombre.setText(usuario.getNombre());
            this.UsuarioInstitucionBoxUsuarios.setSelectedItem(usuario.getInstitucion());
        } else if (consulta.equals("noExiste")) {
            JOptionPane.showMessageDialog(null, "El usuario no existe, proceda a crear usuario");
            this.UsuarioApellido.setEditable(true);
            this.UsuarioInstitucionBoxUsuarios.setEnabled(true);
            this.UsuarioApellido.setEditable(true);
            this.UsuarioContrasena.setEditable(true);
            this.RadioAdministradorGeneral.setEnabled(true);
            this.RadioOperador.setEnabled(true);
            this.RadioJefeDeZona.setEnabled(true);
            this.UsuarioNombre.setEditable(true);
            this.UsuarioEliminarUsuario.setEnabled(false);
            this.UsuarioCrearUsuario.setEnabled(true);
            this.UsuarioEditarUsuario.setEnabled(false);
        } else if (consulta.equals("otraZona")) {
            JOptionPane.showMessageDialog(null, "El usuario es de otra zona, no puedes editarlo");
            this.UsuarioApellido.setEditable(false);
            this.UsuarioInstitucionBoxUsuarios.setEnabled(false);
            this.UsuarioApellido.setEditable(false);
            this.UsuarioContrasena.setEditable(false);
            this.RadioAdministradorGeneral.setEnabled(false);
            this.RadioOperador.setEnabled(false);
            this.RadioJefeDeZona.setEnabled(false);
            this.UsuarioNombre.setEditable(false);
            this.UsuarioEliminarUsuario.setEnabled(false);
            this.UsuarioCrearUsuario.setEnabled(false);
            this.UsuarioEditarUsuario.setEnabled(false);
        } else if (consulta.equals("noPermisos")) {
            JOptionPane.showMessageDialog(null, "No tienes los permisos suficientes para editar este usuario");
            this.UsuarioApellido.setEditable(false);
            this.UsuarioInstitucionBoxUsuarios.setEnabled(false);
            this.UsuarioApellido.setEditable(false);
            this.UsuarioContrasena.setEditable(false);
            this.RadioAdministradorGeneral.setEnabled(false);
            this.RadioOperador.setEnabled(false);
            this.RadioJefeDeZona.setEnabled(false);
            this.UsuarioNombre.setEditable(false);
            this.UsuarioEliminarUsuario.setEnabled(false);
            this.UsuarioCrearUsuario.setEnabled(false);
            this.UsuarioEditarUsuario.setEnabled(false);
        }
        if (operador.getRango().equals("AdministradorGeneral")) {
            this.RadioAdministradorGeneral.setEnabled(true);
            this.RadioOperador.setEnabled(true);
            this.RadioJefeDeZona.setEnabled(true);
        } else if (operador.getRango().equals("JefeDeZona")) {
            this.RadioAdministradorGeneral.setEnabled(false);
            this.RadioOperador.setEnabled(true);
            this.RadioJefeDeZona.setEnabled(false);
        }

    }//GEN-LAST:event_UsuarioComprobarActionPerformed

    private void UsuarioCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioCrearUsuarioActionPerformed
        // TODO add your handling code here:
        String rango = "Operador";
        if (this.RadioOperador.isSelected()) {
            rango = "Operador";
        } else if (this.RadioJefeDeZona.isSelected()) {
            rango = "JefeDeZona";
        } else if (this.RadioAdministradorGeneral.isSelected()) {
            rango = "AdministradorGeneral";
        }
        String textoSinEncriptar = UsuarioContrasena.getText();
        String textoEncriptadoConMD5 = DigestUtils.md5Hex(textoSinEncriptar);
        c.crearOperador(this.UsuarioRut.getText(), textoEncriptadoConMD5, this.UsuarioNombre.getText(), this.UsuarioApellido.getText(), rango, this.UsuarioInstitucionBoxUsuarios.getSelectedItem().toString());
        this.UsuarioApellido.setText("");
        this.UsuarioContrasena.setText("");
        this.UsuarioNombre.setText("");
        this.UsuarioRut.setText("");
        this.UsuarioApellido.setEditable(false);
        this.UsuarioInstitucionBoxUsuarios.setEnabled(false);
        this.UsuarioApellido.setEditable(false);
        this.UsuarioContrasena.setEditable(false);
        this.RadioAdministradorGeneral.setEnabled(false);
        this.RadioOperador.setEnabled(false);
        this.RadioJefeDeZona.setEnabled(false);
        this.UsuarioNombre.setEditable(false);
        this.UsuarioEliminarUsuario.setEnabled(false);
        this.UsuarioCrearUsuario.setEnabled(false);
        this.UsuarioEditarUsuario.setEnabled(false);
    }//GEN-LAST:event_UsuarioCrearUsuarioActionPerformed

    private void UsuarioEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioEliminarUsuarioActionPerformed
        // TODO add your handling code here:
        c.eliminarOperador(this.UsuarioRut.getText());
        this.UsuarioApellido.setText("");
        this.UsuarioContrasena.setText("");
        this.UsuarioNombre.setText("");
        this.UsuarioRut.setText("");
        this.UsuarioApellido.setEditable(false);
        this.UsuarioInstitucionBoxUsuarios.setEnabled(false);
        this.UsuarioApellido.setEditable(false);
        this.UsuarioContrasena.setEditable(false);
        this.RadioAdministradorGeneral.setEnabled(false);
        this.RadioOperador.setEnabled(false);
        this.RadioJefeDeZona.setEnabled(false);
        this.UsuarioNombre.setEditable(false);
        this.UsuarioEliminarUsuario.setEnabled(false);
        this.UsuarioCrearUsuario.setEnabled(false);
        this.UsuarioEditarUsuario.setEnabled(false);
    }//GEN-LAST:event_UsuarioEliminarUsuarioActionPerformed

    private void UsuarioEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioEditarUsuarioActionPerformed
        // TODO add your handling code here:
        String rango = "Operador";
        if (this.RadioOperador.isSelected()) {
            rango = "Operador";
        } else if (this.RadioJefeDeZona.isSelected()) {
            rango = "JefeDeZona";
        } else if (this.RadioAdministradorGeneral.isSelected()) {
            rango = "AdministradorGeneral";
        }
        String textoSinEncriptar = UsuarioContrasena.getText();
        String textoEncriptadoConMD5 = DigestUtils.md5Hex(textoSinEncriptar);
        c.editarOperador(this.UsuarioRut.getText(), textoEncriptadoConMD5, this.UsuarioNombre.getText(), this.UsuarioApellido.getText(), rango, this.UsuarioInstitucionBoxUsuarios.getSelectedItem().toString());
        this.UsuarioApellido.setText("");
        this.UsuarioContrasena.setText("");
        this.UsuarioNombre.setText("");
        this.UsuarioRut.setText("");
        this.UsuarioApellido.setEditable(false);
        this.UsuarioInstitucionBoxUsuarios.setEnabled(false);
        this.UsuarioApellido.setEditable(false);
        this.UsuarioContrasena.setEditable(false);
        this.RadioAdministradorGeneral.setEnabled(false);
        this.RadioOperador.setEnabled(false);
        this.RadioJefeDeZona.setEnabled(false);
        this.UsuarioNombre.setEditable(false);
        this.UsuarioEliminarUsuario.setEnabled(false);
        this.UsuarioCrearUsuario.setEnabled(false);
        this.UsuarioEditarUsuario.setEnabled(false);
    }//GEN-LAST:event_UsuarioEditarUsuarioActionPerformed

    private void comunaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comunaButtonActionPerformed
        // TODO add your handling code here:
        this.menuNormal.setVisible(false);
        this.usuariosPane.setVisible(false);
        this.SectoresPage.setVisible(false);
        this.institucionesPage.setVisible(false);
        this.delincuentesPage.setVisible(false);
        this.delitosPage.setVisible(false);
        this.reportesPage.setVisible(false);
        this.comunaPage.setVisible(true);
    }//GEN-LAST:event_comunaButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.InstitucionesNombre.setEditable(true);
        if (c.comprobarInstitucion(this.InstitucionesCodigo.getText())) {
            JOptionPane.showMessageDialog(null, "La institucion ya exista, proceda a editar o eliminar");
            this.InstitucionesCodigo.setEditable(false);
            this.InstitucionesCrear.setEnabled(false);
            this.InstitucionesEditar.setEnabled(true);
            this.InstitucionesEliminar.setEnabled(true);
            c.setInstitucionesDatos(this.InstitucionesCodigo.getText(), this.InstitucionesNombre);
        } else {
            JOptionPane.showMessageDialog(null, "La institucion no existe, proceda a crearlo");
            this.InstitucionesCodigo.setEditable(false);
            this.InstitucionesCrear.setEnabled(true);
            this.InstitucionesEditar.setEnabled(false);
            this.InstitucionesEliminar.setEnabled(false);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void InstitucionesCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstitucionesCrearActionPerformed
        // TODO add your handling code here:
        if (!this.InstitucionesCodigo.getText().isEmpty() || !this.InstitucionesNombre.getText().isEmpty()) {
            c.crearInstitucion(this.InstitucionesCodigo.getText(), this.InstitucionesNombre.getText());
            institucionesDefault();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese todos los campos");
        }

    }//GEN-LAST:event_InstitucionesCrearActionPerformed

    private void InstitucionesEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstitucionesEliminarActionPerformed
        // TODO add your handling code here:
        c.eliminarInstitucion(this.InstitucionesCodigo.getText());
        institucionesDefault();
    }//GEN-LAST:event_InstitucionesEliminarActionPerformed

    private void InstitucionesEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstitucionesEditarActionPerformed
        // TODO add your handling code here:
        c.editarInstitucion(this.InstitucionesCodigo.getText(), this.InstitucionesNombre.getText());
        institucionesDefault();
    }//GEN-LAST:event_InstitucionesEditarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (c.comprobarSector(this.SectoresCodigo.getText())) {
            JOptionPane.showMessageDialog(null, "El sector ya existe, proceda a editar o eliminar");
            sectoresDefault2();
            c.setSectores(this.SectoresCodigo.getText(), this.SectoresNombre, this.SectoresDescripcion);
        } else {
            JOptionPane.showMessageDialog(null, "El sector no existe, proceda a crear");
            sectoresDefault2();
            this.SectoresCrear.setEnabled(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            // TODO add your handling code here:
            GA.CrearReporterOdenadosAlfabeticamente();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        } catch (WriteException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed
    
    public void sectoresDefault() {
        this.SectoresCodigo.setEditable(true);
        this.SectoresNombre.setEditable(false);
        this.SectoresDescripcion.setEditable(false);
        this.SectoresInstitucion.setEditable(false);
        this.SectoresCrear.setEnabled(false);
        this.SectoresEditar.setEnabled(false);
        this.SectoresEliminar.setEnabled(false);
        this.SectoresCodigo.setText("");
        this.SectoresNombre.setText("");
        this.SectoresDescripcion.setText("");
    }

    public void sectoresDefault2() {
        this.SectoresCodigo.setEditable(false);
        this.SectoresNombre.setEditable(true);
        this.SectoresDescripcion.setEditable(true);
        this.SectoresInstitucion.setEditable(true);
        this.SectoresCrear.setEnabled(false);
        this.SectoresEditar.setEnabled(true);
        this.SectoresEliminar.setEnabled(true);
    }

    public void institucionesDefault() {
        this.InstitucionesCodigo.setEditable(true);
        this.InstitucionesNombre.setEditable(false);
        this.InstitucionesCrear.setEnabled(false);
        this.InstitucionesEditar.setEnabled(false);
        this.InstitucionesEliminar.setEnabled(false);
        this.InstitucionesNombre.setText("");
        this.InstitucionesCodigo.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InstitucionesCodigo;
    private javax.swing.JButton InstitucionesCrear;
    private javax.swing.JButton InstitucionesEditar;
    private javax.swing.JButton InstitucionesEliminar;
    private javax.swing.JTextField InstitucionesNombre;
    private javax.swing.JRadioButton RadioAdministradorGeneral;
    private javax.swing.JRadioButton RadioJefeDeZona;
    private javax.swing.JRadioButton RadioOperador;
    private javax.swing.JTextField SectoresCodigo;
    private javax.swing.JButton SectoresCrear;
    private javax.swing.JTextField SectoresDescripcion;
    private javax.swing.JButton SectoresEditar;
    private javax.swing.JButton SectoresEliminar;
    private javax.swing.JComboBox<String> SectoresInstitucion;
    private javax.swing.JTextField SectoresNombre;
    private javax.swing.JPanel SectoresPage;
    private javax.swing.JTextField UsuarioApellido;
    private javax.swing.JButton UsuarioComprobar;
    private javax.swing.JPasswordField UsuarioContrasena;
    private javax.swing.JButton UsuarioCrearUsuario;
    private javax.swing.JButton UsuarioEditarUsuario;
    private javax.swing.JButton UsuarioEliminarUsuario;
    private javax.swing.JComboBox<String> UsuarioInstitucionBoxUsuarios;
    private javax.swing.JTextField UsuarioNombre;
    private javax.swing.JTextField UsuarioRut;
    private javax.swing.JPanel botonera;
    private javax.swing.JButton comunaButton;
    private javax.swing.JPanel comunaPage;
    private javax.swing.JButton delincuentesButton;
    private javax.swing.JPanel delincuentesPage;
    private javax.swing.JButton delitosButton;
    private javax.swing.JPanel delitosPage;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton institucionesButton;
    private javax.swing.JPanel institucionesPage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel menuNormal;
    private javax.swing.JPanel paginas;
    private javax.swing.JButton reportesButton;
    private javax.swing.JPanel reportesPage;
    private javax.swing.JButton sectoresButton;
    private javax.swing.JLabel userView;
    private javax.swing.JButton usuariosButton;
    private javax.swing.JPanel usuariosPane;
    // End of variables declaration//GEN-END:variables
}
